In [28]:
import pandas as pd 
import requests 
import time 
from bs4 import BeautifulSoup

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1"
}

In [29]:
shoot = pd.read_csv("shooting.csv",sep = "\t")
print(shoot.shape)
shoot.head()

(608, 19)

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
0,1,Myenty Abena,sr SUR,DF,Gaziantep FK,31-149,1994,20.4,1,9,2,22.2,0.44,0.10,0.11,0.50,0,0,Matches
1,2,Tammy Abraham,eng ENG,FW,Beşiktaş,28-220,1997,13.9,7,32,16,50.0,2.31,1.15,0.19,0.38,1,2,Matches
2,3,Yaw Ackah,gh GHA,MF,Kayserispor,26-343,1999,2.0,0,2,1,50.0,0.98,0.49,0.00,0.00,0,0,Matches
3,4,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-327,1997,11.1,1,9,4,44.4,0.81,0.36,0.11,0.25,0,0,Matches
4,5,Dan Agyei,gh GHA,"MF,FW",Kocaelispor,28-343,1997,22.8,5,46,17,37.0,2.02,0.75,0.11,0.29,0,0,Matches

In [30]:
misc = pd.read_csv("misc.csv", sep="\t", encoding="utf-8-sig",skiprows = 1)
print(misc.shape)
misc.head()

(608, 21)

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,CrdY,CrdR,...,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG,Matches
0,1,Myenty Abena,sr SUR,DF,Gaziantep FK,31-151,1994,20.4,2,1,...,22,17,1,1,14,21,NaN,NaN,1,Matches
1,2,Tammy Abraham,eng ENG,FW,Beşiktaş,28-222,1997,13.9,3,0,...,25,12,9,4,6,2,NaN,NaN,0,Matches
2,3,Yaw Ackah,gh GHA,MF,Kayserispor,26-345,1999,2.0,0,0,...,2,2,0,0,1,0,NaN,NaN,0,Matches
3,4,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-329,1997,11.1,3,0,...,16,5,1,3,13,15,NaN,NaN,0,Matches
4,5,Dan Agyei,gh GHA,"MF,FW",Kocaelispor,28-345,1997,22.8,0,0,...,27,26,7,65,4,3,NaN,NaN,0,Matches

In [31]:
play = pd.read_csv("playing.csv", sep="\t", encoding="utf-8",skiprows = 1)
print(play.shape)
play.head()

(739, 25)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Min,Mn/MP,...,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,Matches
0,1,Alp Abay,NaN,DF,Antalyaspor,20-001,2006,0,NaN,NaN,...,0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Matches
1,2,Myenty Abena,sr SUR,DF,Gaziantep FK,31-151,1994,23,"1,836",80,...,3,44,4,1.09,27,40,-13,-0.64,-0.56,Matches
2,3,Tammy Abraham,eng ENG,FW,Beşiktaş,28-222,1997,18,"1,247",69,...,3,24,0,1.78,22,17,+5,+0.36,-0.37,Matches
3,4,Yaw Ackah,gh GHA,MF,Kayserispor,26-345,1999,3,184,61,...,1,31,0,0.67,1,3,-2,-0.98,+0.12,Matches
4,5,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-329,1997,12,"1,001",83,...,1,11,1,1.67,16,11,+5,+0.45,-0.19,Matches

In [32]:
std = pd.read_csv("standard.csv", sep="\t", encoding = "utf-8",skiprows = 1)
print(std.shape)
std.head()

(608, 25)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Matches
0,1,Myenty Abena,sr SUR,DF,Gaziantep FK,31-151,1994,23,20,"1,836",...,0,0,2,1,0.05,0.05,0.10,0.05,0.10,Matches
1,2,Tammy Abraham,eng ENG,FW,Beşiktaş,28-222,1997,18,15,"1,247",...,1,2,3,0,0.51,0.07,0.58,0.43,0.51,Matches
2,3,Yaw Ackah,gh GHA,MF,Kayserispor,26-345,1999,3,2,184,...,0,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches
3,4,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-329,1997,12,11,"1,001",...,0,0,3,0,0.09,0.09,0.18,0.09,0.18,Matches
4,5,Dan Agyei,gh GHA,"MF,FW",Kocaelispor,28-345,1997,30,22,"2,052",...,0,0,0,0,0.22,0.00,0.22,0.22,0.22,Matches

In [38]:
transfer = pd.read_csv("transfermarkt.csv", encoding = "utf-8")
print(transfer.shape)
transfer.head()

(515, 3)

            Player        Takim Piyasa_Degeri
0    Uğurcan Çakır  Galatasaray  15.00 mil. €
1     Günay Güvenç  Galatasaray     300 bin €
2      Batuhan Şen  Galatasaray     200 bin €
3  Enes Emre Büyük  Galatasaray             -
4   Wilfried Singo  Galatasaray  25.00 mil. €

In [39]:
print(transfer.columns.tolist())
print(transfer.shape)
transfer.head()

['Player', 'Takim', 'Piyasa_Degeri']
(515, 3)

            Player        Takim Piyasa_Degeri
0    Uğurcan Çakır  Galatasaray  15.00 mil. €
1     Günay Güvenç  Galatasaray     300 bin €
2      Batuhan Şen  Galatasaray     200 bin €
3  Enes Emre Büyük  Galatasaray             -
4   Wilfried Singo  Galatasaray  25.00 mil. €

In [10]:
# Tüm 4 dataframe için başlık temizliği
std = std[std["Player"] != "Player"]
shooting = shooting[shooting["Player"] != "Player"]
misc = misc[misc["Player"] != "Player"]
playing = playing[playing["Player"] != "Player"]

# Şimdi sayı dönüşümünü yap
std["Min"] = std["Min"].str.replace(",", "").astype(int)

# Kontrol
print(std["Min"].dtype)
print(std.shape)

int64
(585, 25)

In [11]:
sayi_sutunlari = ["MP", "Starts", "90s", "Gls", "Ast", "PK", "PKatt", "CrdY", "CrdR"]
std[sayi_sutunlari] = std[sayi_sutunlari].apply(pd.to_numeric, errors="coerce")

print(std.dtypes)
print(std.shape)

Rk          object
Player      object
Nation      object
Pos         object
Squad       object
Age         object
Born        object
MP           int64
Starts       int64
Min          int64
90s        float64
Gls          int64
Ast          int64
G+A         object
G-PK        object
PK           int64
PKatt        int64
CrdY         int64
CrdR         int64
Gls.1       object
Ast.1       object
G+A.1       object
G-PK.1      object
G+A-PK      object
Matches     object
dtype: object
(585, 25)

In [12]:
# SHOOTING
shooting = shooting[shooting["Player"] != "Player"]
sayi_shooting = ["Sh", "SoT", "SoT%", "Sh/90", "SoT/90", "G/Sh", "G/SoT"]
shooting[sayi_shooting] = shooting[sayi_shooting].apply(pd.to_numeric, errors="coerce")

# MISC
misc = misc[misc["Player"] != "Player"]
sayi_misc = ["Fls", "Fld", "Off", "Crs", "Int", "TklW", "2CrdY"]
misc[sayi_misc] = misc[sayi_misc].apply(pd.to_numeric, errors="coerce")

# PLAYING
playing = playing[playing["Player"] != "Player"]
sayi_playing = ["Mn/MP", "Mn/Start", "Compl", "Subs", "Mn/Sub", "unSub", "PPM"]
playing[sayi_playing] = playing[sayi_playing].apply(pd.to_numeric, errors="coerce")

In [14]:
std_temiz = std[["Player", "Nation", "Pos", "Squad", "Age", "Born", "MP", "Starts", "Min", "90s", "Gls", "Ast", "PK", "PKatt", "CrdY", "CrdR"]]
shooting_temiz = shooting[["Player", "Squad", "Sh", "SoT", "SoT%", "Sh/90", "SoT/90", "G/Sh", "G/SoT"]]
misc_temiz = misc[["Player", "Squad", "Fls", "Fld", "Off", "Crs", "Int", "TklW", "2CrdY"]]
playing_temiz = playing[["Player", "Squad", "Mn/MP", "Mn/Start", "Compl", "Subs", "Mn/Sub", "unSub", "PPM"]]

In [15]:
print("std_temiz:", std_temiz.shape)
print("shooting_temiz:", shooting_temiz.shape)
print("misc_temiz:", misc_temiz.shape)
print("playing_temiz:", playing_temiz.shape)

std_temiz: (585, 16)
shooting_temiz: (585, 9)
misc_temiz: (585, 9)
playing_temiz: (711, 9)

In [18]:
print("STD tekrarlananlar:")
print(std_temiz["Player"].value_counts()[std_temiz["Player"].value_counts() > 1])
print()
print("SHOOTING tekrarlananlar:")
print(shooting_temiz["Player"].value_counts()[shooting_temiz["Player"].value_counts() > 1])
print()
print("MISC tekrarlananlar:")
print(misc_temiz["Player"].value_counts()[misc_temiz["Player"].value_counts() > 1])
print()
print("PLAYING tekrarlananlar:")
print(playing_temiz["Player"].value_counts()[playing_temiz["Player"].value_counts() > 1])

STD tekrarlananlar:
Player
Jakub Kałuziński       2
Berkan Kutlu           2
Eyüp Aydın             2
Cengiz Ünder           2
Deniz Turuc            2
Rayyan Baniya          2
Cenk Tosun             2
Mert Günok             2
Semih Güler            2
Rodrigo Becão          2
Tayyib Talha Sanuç     2
Ernest Muçi            2
Nihad Mujakić          2
Arif Boşluk            2
Anthony Musaba         2
Umut Nayir             2
Uğurcan Çakır          2
Kazeem Olaigbe         2
Junior Olaitan         2
İrfan Can Eğribayat    2
Cihan Çanak            2
Bartuğ Elmaz           2
Gökhan Sazdağı         2
Denis Drăguș           2
Emir Ortakaya          2
Ruan                   2
Yalçın Kayan           2
Dal Varesanovic        2
Kerem Demirbay         2
İrfan Kahveci          2
Kazımcan Karataş       2
Melih Kabasakal        2
Name: count, dtype: int64

SHOOTING tekrarlananlar:
Player
Jakub Kałuziński       2
Berkan Kutlu           2
Eyüp Aydın             2
Cengiz Ünder           2
Deniz Turuc            2
Rayyan Baniya          2
Cenk Tosun             2
Mert Günok             2
Semih Güler            2
Rodrigo Becão          2
Tayyib Talha Sanuç     2
Ernest Muçi            2
Nihad Mujakić          2
Arif Boşluk            2
Anthony Musaba         2
Umut Nayir             2
Uğurcan Çakır          2
Kazeem Olaigbe         2
Junior Olaitan         2
İrfan Can Eğribayat    2
Cihan Çanak            2
Bartuğ Elmaz           2
Gökhan Sazdağı         2
Denis Drăguș           2
Emir Ortakaya          2
Ruan                   2
Yalçın Kayan           2
Dal Varesanovic        2
Kerem Demirbay         2
İrfan Kahveci          2
Kazımcan Karataş       2
Melih Kabasakal        2
Name: count, dtype: int64

MISC tekrarlananlar:
Player
Jakub Kałuziński       2
Berkan Kutlu           2
Eyüp Aydın             2
Cengiz Ünder           2
Deniz Turuc            2
Rayyan Baniya          2
Cenk Tosun             2
Mert Günok             2
Semih Güler            2
Rodrigo Becão          2
Tayyib Talha Sanuç     2
Ernest Muçi            2
Nihad Mujakić          2
Arif Boşluk            2
Anthony Musaba         2
Umut Nayir             2
Uğurcan Çakır          2
Kazeem Olaigbe         2
Junior Olaitan         2
İrfan Can Eğribayat    2
Cihan Çanak            2
Bartuğ Elmaz           2
Gökhan Sazdağı         2
Denis Drăguș           2
Emir Ortakaya          2
Ruan                   2
Yalçın Kayan           2
Dal Varesanovic        2
Kerem Demirbay         2
İrfan Kahveci          2
Kazımcan Karataş       2
Melih Kabasakal        2
Name: count, dtype: int64

PLAYING tekrarlananlar:
Player
Kazımcan Karataş        2
Anthony Musaba          2
Dal Varesanovic         2
Eyüp Aydın              2
Cengiz Ünder            2
Mert Günok              2
Deniz Turuc             2
Semih Güler             2
Cenk Tosun              2
Rayyan Baniya           2
Baran Gezek             2
Tayyib Talha Sanuç      2
Ernest Muçi             2
Nihad Mujakić           2
Arif Boşluk             2
Umut Nayir              2
Seyfettin Anıl Yaşar    2
Bartuğ Elmaz            2
Uğurcan Çakır           2
Kazeem Olaigbe          2
Junior Olaitan          2
İrfan Can Eğribayat     2
Gökhan Sazdağı          2
Cihan Çanak             2
Denis Drăguș            2
Emir Ortakaya           2
Ruan                    2
Kerem Demirbay          2
Mehmet Öztürk           2
Bedirhan Özyurt         2
Berkan Kutlu            2
Rodrigo Becão           2
Jankat Yilmaz           2
Jakub Kałuziński        2
Melih Kabasakal         2
İrfan Kahveci           2
Yalçın Kayan            2
Name: count, dtype: int64

In [19]:
std_temiz = std_temiz.drop_duplicates(subset="Player", keep=False)
shooting_temiz = shooting_temiz.drop_duplicates(subset="Player", keep=False)
misc_temiz = misc_temiz.drop_duplicates(subset="Player", keep=False)
playing_temiz = playing_temiz.drop_duplicates(subset="Player", keep=False)

print("std_temiz:", std_temiz.shape)
print("shooting_temiz:", shooting_temiz.shape)
print("misc_temiz:", misc_temiz.shape)
print("playing_temiz:", playing_temiz.shape)

std_temiz: (521, 16)
shooting_temiz: (521, 9)
misc_temiz: (521, 9)
playing_temiz: (637, 9)

In [20]:
birlesik = std_temiz.merge(shooting_temiz, on=["Player", "Squad"], how="inner")
print(birlesik.shape)

(521, 23)

In [22]:
birlesik = birlesik.merge(misc_temiz, on=["Player","Squad"], how = "inner")
print("misc ile  birlestirildi: ", birlesik.shape)
birlesik = birlesik.merge(playing_temiz, on=["Player","Squad"], how = "inner")
print("playing ile birlestirildi: ", birlesik.shape)

misc ile  birlestirildi:  (521, 30)
playing ile birlestirildi:  (517, 37)

In [23]:
std_playerlar = set(std_temiz["Player"])
playing_playerlar = set(playing_temiz["Player"])

kayip = std_playerlar - playing_playerlar
print("Std'de olup playing'de olmayanlar:", kayip)

Std'de olup playing'de olmayanlar: {'Jankat Yilmaz', 'Baran Gezek', 'Bedirhan Özyurt', 'Seyfettin Anıl Yaşar'}

In [40]:
print(transfer.columns.tolist())
print(transfer.head())

['Player', 'Takim', 'Piyasa_Degeri']
            Player        Takim Piyasa_Degeri
0    Uğurcan Çakır  Galatasaray  15.00 mil. €
1     Günay Güvenç  Galatasaray     300 bin €
2      Batuhan Şen  Galatasaray     200 bin €
3  Enes Emre Büyük  Galatasaray             -
4   Wilfried Singo  Galatasaray  25.00 mil. €

In [41]:
print("FBref takımları:", sorted(birlesik["Squad"].unique()))
print("Transfermarkt takımları:", sorted(transfer["Takim"].unique()))

FBref takımları: ['Alanyaspor', 'Antalyaspor', 'Başakşehir', 'Beşiktaş', 'Eyüpspor', 'Fatih Karagümrük', 'Fenerbahçe', 'Galatasaray', 'Gaziantep FK', 'Gençlerbirliği', 'Göztepe', 'Kasımpaşa', 'Kayserispor', 'Kocaelispor', 'Konyaspor', 'Rizespor', 'Samsunspor', 'Trabzonspor']
Transfermarkt takımları: ['Alanyaspor', 'Antalyaspor', 'Basaksehir', 'Besiktas', 'Eyupspor', 'Fatih-Karagumruk', 'Fenerbahce', 'Galatasaray', 'Gaziantep-fk', 'Genclerbirligi', 'Goztepe', 'Kasimpasa', 'Kayserispor', 'Kocaelispor', 'Konyaspor', 'Samsunspor', 'Trabzonspor', 'caykur-rizespor']

In [42]:
transfer = transfer.rename(columns={"Takim": "Squad"})
print(transfer.columns.tolist())

['Player', 'Squad', 'Piyasa_Degeri']

In [43]:
transfer.head()

            Player        Squad Piyasa_Degeri
0    Uğurcan Çakır  Galatasaray  15.00 mil. €
1     Günay Güvenç  Galatasaray     300 bin €
2      Batuhan Şen  Galatasaray     200 bin €
3  Enes Emre Büyük  Galatasaray             -
4   Wilfried Singo  Galatasaray  25.00 mil. €

In [44]:
print("FBref:", sorted(birlesik["Squad"].unique()))
print()
print("Transfermarkt:", sorted(transfer["Squad"].unique()))

FBref: ['Alanyaspor', 'Antalyaspor', 'Başakşehir', 'Beşiktaş', 'Eyüpspor', 'Fatih Karagümrük', 'Fenerbahçe', 'Galatasaray', 'Gaziantep FK', 'Gençlerbirliği', 'Göztepe', 'Kasımpaşa', 'Kayserispor', 'Kocaelispor', 'Konyaspor', 'Rizespor', 'Samsunspor', 'Trabzonspor']

Transfermarkt: ['Alanyaspor', 'Antalyaspor', 'Basaksehir', 'Besiktas', 'Eyupspor', 'Fatih-Karagumruk', 'Fenerbahce', 'Galatasaray', 'Gaziantep-fk', 'Genclerbirligi', 'Goztepe', 'Kasimpasa', 'Kayserispor', 'Kocaelispor', 'Konyaspor', 'Samsunspor', 'Trabzonspor', 'caykur-rizespor']

In [45]:
takim_haritasi = {
    "Basaksehir": "Başakşehir",
    "Besiktas": "Beşiktaş",
    "Eyupspor": "Eyüpspor",
    "Fatih-Karagumruk": "Fatih Karagümrük",
    "Fenerbahce": "Fenerbahçe",
    "Gaziantep-fk": "Gaziantep FK",
    "Genclerbirligi": "Gençlerbirliği",
    "Goztepe": "Göztepe",
    "Kasimpasa": "Kasımpaşa",
    "caykur-rizespor": "Rizespor"
}

transfer["Squad"] = transfer["Squad"].replace(takim_haritasi)

In [46]:
print(sorted(transfer["Squad"].unique()))

['Alanyaspor', 'Antalyaspor', 'Başakşehir', 'Beşiktaş', 'Eyüpspor', 'Fatih Karagümrük', 'Fenerbahçe', 'Galatasaray', 'Gaziantep FK', 'Gençlerbirliği', 'Göztepe', 'Kasımpaşa', 'Kayserispor', 'Kocaelispor', 'Konyaspor', 'Rizespor', 'Samsunspor', 'Trabzonspor']

In [47]:
fbref_oyuncular = set(birlesik["Player"])
transfer_oyuncular = set(transfer["Player"])

ortak = fbref_oyuncular & transfer_oyuncular
print("Toplam FBref:", len(fbref_oyuncular))
print("Toplam Transfermarkt:", len(transfer_oyuncular))
print("Tam eşleşen:", len(ortak))
print("FBref'te olup Transfermarkt'ta olmayan:", len(fbref_oyuncular - transfer_oyuncular))

Toplam FBref: 517
Toplam Transfermarkt: 515
Tam eşleşen: 311
FBref'te olup Transfermarkt'ta olmayan: 206

In [53]:
from thefuzz import process

def en_yakin_eslesme(isim, secenekler, esik=85):
    """En yakın eşleşmeyi bulur, eşik altıysa None döner"""
    sonuc = process.extractOne(isim, secenekler)
    if sonuc and sonuc[1] >= esik:
        return sonuc[0]
    return None

In [54]:
fbref_liste = birlesik["Player"].tolist()
transfer["FBref_Eslesme"] = transfer["Player"].apply(lambda x: en_yakin_eslesme(x, fbref_liste))

# Kontrol
print("Eşleşen:", transfer["FBref_Eslesme"].notna().sum())
print("Eşleşmeyen:", transfer["FBref_Eslesme"].isna().sum())

Eşleşen: 419
Eşleşmeyen: 96

In [55]:
eslesmeyenler = transfer[transfer["FBref_Eslesme"].isna()]
print(eslesmeyenler[["Player", "Squad"]].head(30))

                Player        Squad
0        Uğurcan Çakır  Galatasaray
2          Batuhan Şen  Galatasaray
3      Enes Emre Büyük  Galatasaray
26       Armando Güner  Galatasaray
31          Mert Günok   Fenerbahçe
47     Abdou Aziz Fall   Fenerbahçe
54      Anthony Musaba   Fenerbahçe
58    Onuralp Çevikkan  Trabzonspor
60      Erol Can Çolak  Trabzonspor
64         Arda Öztürk  Trabzonspor
65      Taha Emre İnce  Trabzonspor
76         Ernest Muci  Trabzonspor
79          Edin Visca  Trabzonspor
83          Umut Nayir  Trabzonspor
86         Emre Bilgin     Beşiktaş
87          Emir Yaşar     Beşiktaş
96      Gökhan Sazdağı     Beşiktaş
107       Vaclav Cerny     Beşiktaş
108       Cengiz Ünder     Beşiktaş
113  Ekrem Kılıçarslan      Göztepe
114       Şamil Öztürk      Göztepe
115        Nevzat Üzel      Göztepe
122        Erkam Kömür      Göztepe
124    Novatus Miroshi      Göztepe
126       Furkan Malak      Göztepe
141     Volkan Babacan   Başakşehir
142       Luca Stancic   Başakşehir
148   Kazımcan Karataş   Başakşehir
152   Jakub Kaluzinski   Başakşehir
160       Berkay Aslan   Başakşehir

In [56]:
# Eşleşen ama isimleri farklı olanları göster
farkli_eslesmeler = transfer[
    (transfer["FBref_Eslesme"].notna()) & 
    (transfer["Player"] != transfer["FBref_Eslesme"])
][["Player", "FBref_Eslesme", "Squad"]]

print("Farklı eşleşme sayısı:", len(farkli_eslesmeler))
print()
print(farkli_eslesmeler.head(30))

Farklı eşleşme sayısı: 108

                  Player                  FBref_Eslesme        Squad
25        Yáser Asprilla                 Yaser Asprilla  Galatasaray
32     Engin Can Biterge                      Can Keles   Fenerbahçe
37      Kamil Efe Üregen                  Kamil Çörekçi   Fenerbahçe
50     Mert Hakan Yandaş                    Mert Müldür   Fenerbahçe
53         Dorgeles Nene                  Nene Dorgeles   Fenerbahçe
55              Emre Mor                Yunus Emre Çift   Fenerbahçe
56         Sidiki Chérif                  Sidiki Cherif   Fenerbahçe
59        Ahmet Yıldırım           Ahmet Doğan Yıldırım  Trabzonspor
61       Arseniy Batagov                Arsenii Batahov  Trabzonspor
63          Stefan Savic                   Stefan Savić  Trabzonspor
70      Salih Malkoçoğlu               Salih Malkoçoglu  Trabzonspor
80     Onuralp Çakıroğlu              Onuralp Çakiroğlu  Trabzonspor
90         Emirhan Topçu                     Emir Topçu     Beşiktaş
92        Felix Uduokhai            Ohis Felix Uduokhai     Beşiktaş
94          Amir Murillo           Michael Amir Murillo     Beşiktaş
103       Junior Olaitan  Sergio Antonio De Luiz Junior     Beşiktaş
110         Hyeon-gyu Oh                   Oh Hyeon-gyu     Beşiktaş
117        Malcom Bokele                  Malcom Bokélé      Göztepe
127   Arda Okan Kurtulan                  Arda Kurtulan      Göztepe
130          Amin Cherni                   Amine Cherni      Göztepe
135                 Juan                    Juan Santos      Göztepe
138                  Jeh                   Jeferson Jeh      Göztepe
140        Doğan Alemdar           Ahmet Doğan Yıldırım   Başakşehir
156        Miguel Crespo                         Crespo   Başakşehir
159           Ivan Brnic                     Ivan Brnić   Başakşehir
161  Abbosbek Fayzullaev           Abbosbek Fayzullayev   Başakşehir
162           Yusuf Sarı                     Yusuf Sari   Başakşehir
166        Nuno Da Costa                  Nuno da Costa   Başakşehir
168  İrfan Can Eğribayat                      Can Keles   Samsunspor
172      Toni Borevković                Toni Borevkovic   Samsunspor

In [57]:
def takim_bazli_eslesme(player, squad, fbref_df, esik=75):
    """Sadece aynı takımdaki oyuncularla eşleştir"""
    ayni_takim = fbref_df[fbref_df["Squad"] == squad]["Player"].tolist()
    
    if not ayni_takim:
        return None
    
    sonuc = process.extractOne(player, ayni_takim)
    if sonuc and sonuc[1] >= esik:
        return sonuc[0]
    return None

transfer["FBref_Eslesme"] = transfer.apply(
    lambda row: takim_bazli_eslesme(row["Player"], row["Squad"], birlesik), 
    axis=1
)

print("Eşleşen:", transfer["FBref_Eslesme"].notna().sum())
print("Eşleşmeyen:", transfer["FBref_Eslesme"].isna().sum())

Eşleşen: 410
Eşleşmeyen: 105

In [58]:
farkli_eslesmeler = transfer[
    (transfer["FBref_Eslesme"].notna()) & 
    (transfer["Player"] != transfer["FBref_Eslesme"])
][["Player", "FBref_Eslesme", "Squad"]]

print("Farklı eşleşme sayısı:", len(farkli_eslesmeler))
print()
print(farkli_eslesmeler.head(40))

Farklı eşleşme sayısı: 99

                      Player         FBref_Eslesme         Squad
25            Yáser Asprilla        Yaser Asprilla   Galatasaray
50         Mert Hakan Yandaş           Mert Müldür    Fenerbahçe
53             Dorgeles Nene         Nene Dorgeles    Fenerbahçe
56             Sidiki Chérif         Sidiki Cherif    Fenerbahçe
59            Ahmet Yıldırım  Ahmet Doğan Yıldırım   Trabzonspor
61           Arseniy Batagov       Arsenii Batahov   Trabzonspor
63              Stefan Savic          Stefan Savić   Trabzonspor
70          Salih Malkoçoğlu      Salih Malkoçoglu   Trabzonspor
79                Edin Visca            Edin Višća   Trabzonspor
80         Onuralp Çakıroğlu     Onuralp Çakiroğlu   Trabzonspor
90             Emirhan Topçu            Emir Topçu      Beşiktaş
92            Felix Uduokhai   Ohis Felix Uduokhai      Beşiktaş
94              Amir Murillo  Michael Amir Murillo      Beşiktaş
107             Vaclav Cerny          Václav Černý      Beşiktaş
110             Hyeon-gyu Oh          Oh Hyeon-gyu      Beşiktaş
117            Malcom Bokele         Malcom Bokélé       Göztepe
127       Arda Okan Kurtulan         Arda Kurtulan       Göztepe
130              Amin Cherni          Amine Cherni       Göztepe
135                     Juan           Juan Santos       Göztepe
138                      Jeh          Jeferson Jeh       Göztepe
156            Miguel Crespo                Crespo    Başakşehir
159               Ivan Brnic            Ivan Brnić    Başakşehir
161      Abbosbek Fayzullaev  Abbosbek Fayzullayev    Başakşehir
162               Yusuf Sarı            Yusuf Sari    Başakşehir
166            Nuno Da Costa         Nuno da Costa    Başakşehir
172          Toni Borevković       Toni Borevkovic    Samsunspor
173            Lubomir Satka         Ľubomír Šatka    Samsunspor
175        Ali Badra Diabaté           Ali Diabaté    Samsunspor
201     Aleksandar Jovanovic  Aleksandar Jovanović   Kocaelispor
205           Hrvoje Smolcic        Hrvoje Smolčić   Kocaelispor
214              Habib Keïta           Habib Keita   Kocaelispor
222                Can Keleş             Can Keles   Kocaelispor
224           Bruno Petkovic        Bruno Petković   Kocaelispor
226              Ahmet Sağat           Ahmet Sagat   Kocaelispor
229              Burak Bozan   Mustafa Burak Bozan  Gaziantep FK
235            Nazım Sangaré         Nazim Sangaré  Gaziantep FK
239           Salem M'Bakata        Salem M'bakata  Gaziantep FK
244         Kacper Kozlowski      Kacper Kozłowski  Gaziantep FK
246  Victor Ntino-Emo Gidado         Victor Gidado  Gaziantep FK
247           Yusuf Kabadayi        Yusuf Kabadayı  Gaziantep FK

In [59]:
# Eşleşmeyen oyuncuları at (FBref'te zaten yoklar)
transfer_temiz = transfer.dropna(subset=["FBref_Eslesme"])

# Birleştir
nihai = birlesik.merge(
    transfer_temiz[["FBref_Eslesme", "Piyasa_Degeri"]],
    left_on="Player",
    right_on="FBref_Eslesme",
    how="inner"
)

# FBref_Eslesme sütununu sil (artık gereksiz)
nihai = nihai.drop(columns=["FBref_Eslesme"])

print("Nihai shape:", nihai.shape)
print(nihai.head())

Nihai shape: (410, 38)
                  Player  Nation    Pos         Squad     Age  Born  MP  \
0           Myenty Abena  sr SUR     DF  Gaziantep FK  31-151  1994  23
1       Emmanuel Agbadou  ci CIV     DF      Beşiktaş  28-329  1997  12
2              Dan Agyei  gh GHA  MF,FW   Kocaelispor  28-345  1997  30
3  Youssef Aït Bennasser  ma MAR  MF,DF   Kayserispor  29-309  1996  21
4          Samet Akaydın  tr TUR     DF      Rizespor  32-060  1994  29

   Starts   Min   90s  ...  TklW  2CrdY  Mn/MP  Mn/Start  Compl  Subs  Mn/Sub  \
0      20  1836  20.4  ...    21      0   80.0      85.0     17     3    44.0
1      11  1001  11.1  ...    15      0   83.0      90.0     11     1    11.0
2      22  2052  22.8  ...     3      0   68.0      85.0      8     8    24.0
3      19  1468  16.3  ...    14      0   70.0      74.0      9     2    32.0
4      29  2566  28.5  ...    25      1   88.0      88.0     24     0     NaN

   unSub   PPM  Piyasa_Degeri
0      4  1.09      600 bin €
1      1  1.67   18.00 mil. €
2      1  1.10      800 bin €
3      0  0.95    1.00 mil. €
4      0  1.28    1.20 mil. €

[5 rows x 38 columns]