In [1]:
import pandas as pd 
import requests 
import time 
from bs4 import BeautifulSoup

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1"
}

/Users/ates/transfer-deger-tahmini/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
shoot = pd.read_csv("shooting.csv",sep = "\t")
print(shoot.shape)
shoot.head()

(608, 19)

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
0,1,Myenty Abena,sr SUR,DF,Gaziantep FK,31-149,1994,20.4,1,9,2,22.2,0.44,0.10,0.11,0.50,0,0,Matches
1,2,Tammy Abraham,eng ENG,FW,Beşiktaş,28-220,1997,13.9,7,32,16,50.0,2.31,1.15,0.19,0.38,1,2,Matches
2,3,Yaw Ackah,gh GHA,MF,Kayserispor,26-343,1999,2.0,0,2,1,50.0,0.98,0.49,0.00,0.00,0,0,Matches
3,4,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-327,1997,11.1,1,9,4,44.4,0.81,0.36,0.11,0.25,0,0,Matches
4,5,Dan Agyei,gh GHA,"MF,FW",Kocaelispor,28-343,1997,22.8,5,46,17,37.0,2.02,0.75,0.11,0.29,0,0,Matches

In [4]:
misc = pd.read_csv("misc.csv", sep="\t", encoding="utf-8-sig",skiprows = 1)
print(misc.shape)
misc.head()

(608, 21)

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,CrdY,CrdR,...,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG,Matches
0,1,Myenty Abena,sr SUR,DF,Gaziantep FK,31-151,1994,20.4,2,1,...,22,17,1,1,14,21,NaN,NaN,1,Matches
1,2,Tammy Abraham,eng ENG,FW,Beşiktaş,28-222,1997,13.9,3,0,...,25,12,9,4,6,2,NaN,NaN,0,Matches
2,3,Yaw Ackah,gh GHA,MF,Kayserispor,26-345,1999,2.0,0,0,...,2,2,0,0,1,0,NaN,NaN,0,Matches
3,4,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-329,1997,11.1,3,0,...,16,5,1,3,13,15,NaN,NaN,0,Matches
4,5,Dan Agyei,gh GHA,"MF,FW",Kocaelispor,28-345,1997,22.8,0,0,...,27,26,7,65,4,3,NaN,NaN,0,Matches

In [5]:
play = pd.read_csv("playing.csv", sep="\t", encoding="utf-8",skiprows = 1)
print(play.shape)
play.head()

(739, 25)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Min,Mn/MP,...,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,Matches
0,1,Alp Abay,NaN,DF,Antalyaspor,20-001,2006,0,NaN,NaN,...,0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Matches
1,2,Myenty Abena,sr SUR,DF,Gaziantep FK,31-151,1994,23,"1,836",80,...,3,44,4,1.09,27,40,-13,-0.64,-0.56,Matches
2,3,Tammy Abraham,eng ENG,FW,Beşiktaş,28-222,1997,18,"1,247",69,...,3,24,0,1.78,22,17,+5,+0.36,-0.37,Matches
3,4,Yaw Ackah,gh GHA,MF,Kayserispor,26-345,1999,3,184,61,...,1,31,0,0.67,1,3,-2,-0.98,+0.12,Matches
4,5,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-329,1997,12,"1,001",83,...,1,11,1,1.67,16,11,+5,+0.45,-0.19,Matches

In [12]:
std = pd.read_csv("standard.csv", sep="\t", encoding = "utf-8",skiprows = 1)
print(std.shape)
std.head()

(608, 25)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Matches
0,1,Myenty Abena,sr SUR,DF,Gaziantep FK,31-151,1994,23,20,"1,836",...,0,0,2,1,0.05,0.05,0.10,0.05,0.10,Matches
1,2,Tammy Abraham,eng ENG,FW,Beşiktaş,28-222,1997,18,15,"1,247",...,1,2,3,0,0.51,0.07,0.58,0.43,0.51,Matches
2,3,Yaw Ackah,gh GHA,MF,Kayserispor,26-345,1999,3,2,184,...,0,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches
3,4,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-329,1997,12,11,"1,001",...,0,0,3,0,0.09,0.09,0.18,0.09,0.18,Matches
4,5,Dan Agyei,gh GHA,"MF,FW",Kocaelispor,28-345,1997,30,22,"2,052",...,0,0,0,0,0.22,0.00,0.22,0.22,0.22,Matches

In [13]:
transfer = pd.read_csv("transfermarkt.csv",sep = ",",encoding = "utf-8")
print(transfer.shape)
transfer.head()

(515, 3)

            Player        Takim Piyasa_Degeri
0    Uğurcan Çakır  Galatasaray  15.00 mil. €
1     Günay Güvenç  Galatasaray     300 bin €
2      Batuhan Şen  Galatasaray     200 bin €
3  Enes Emre Büyük  Galatasaray             -
4   Wilfried Singo  Galatasaray  25.00 mil. €

In [14]:
print(transfer.columns.tolist())
print(transfer.shape)
transfer.head()

['Player', 'Takim', 'Piyasa_Degeri']
(515, 3)

            Player        Takim Piyasa_Degeri
0    Uğurcan Çakır  Galatasaray  15.00 mil. €
1     Günay Güvenç  Galatasaray     300 bin €
2      Batuhan Şen  Galatasaray     200 bin €
3  Enes Emre Büyük  Galatasaray             -
4   Wilfried Singo  Galatasaray  25.00 mil. €

In [19]:
print("STANDARD:", std.columns.tolist())
print("                                    ")
print("SHOOTING:", shoot.columns.tolist())

print("                                    ")
print("MISC:", misc.columns.tolist())

print("                                    ")
print("PLAYING:", play.columns.tolist())

print("                                    ")
print("TRANSFER:", transfer.columns.tolist())

STANDARD: ['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK', 'Matches']

SHOOTING: ['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'Gls', 'Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'PK', 'PKatt', 'Matches']

MISC: ['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'PKwon', 'PKcon', 'OG', 'Matches']

PLAYING: ['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Min', 'Mn/MP', 'Min%', '90s', 'Starts', 'Mn/Start', 'Compl', 'Subs', 'Mn/Sub', 'unSub', 'PPM', 'onG', 'onGA', '+/-', '+/-90', 'On-Off', 'Matches']

TRANSFER: ['Player', 'Takim', 'Piyasa_Degeri']

In [21]:
std_temiz = std[
                ["Player","Nation","Pos","Squad","Age",
                "Born","MP","Starts","Min","90s","Gls",
                "Ast","PK","PKatt","CrdY","CrdR"]]

shooting_temiz = shoot[
                    ["Player","Squad","Sh","SoT","SoT%",
                    "Sh/90","SoT/90","G/Sh","G/SoT"]]

misc_temiz = misc[
                ["Player","Squad","Fls","Fld",
                "Off","Crs","Int","TklW","2CrdY"]]

playing_temiz = play[
                    ["Player","Squad","Mn/MP","Mn/Start",
                    "Compl","Subs","Mn/Sub","unSub","PPM"]]

In [22]:
print(std_temiz.shape)
std_temiz.head()

(608, 16)

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,PK,PKatt,CrdY,CrdR
0,Myenty Abena,sr SUR,DF,Gaziantep FK,31-151,1994,23,20,"1,836",20.4,1,1,0,0,2,1
1,Tammy Abraham,eng ENG,FW,Beşiktaş,28-222,1997,18,15,"1,247",13.9,7,1,1,2,3,0
2,Yaw Ackah,gh GHA,MF,Kayserispor,26-345,1999,3,2,184,2.0,0,0,0,0,0,0
3,Emmanuel Agbadou,ci CIV,DF,Beşiktaş,28-329,1997,12,11,"1,001",11.1,1,1,0,0,3,0
4,Dan Agyei,gh GHA,"MF,FW",Kocaelispor,28-345,1997,30,22,"2,052",22.8,5,0,0,0,0,0

In [23]:
print(shooting_temiz.shape)
shooting_temiz.head()

(608, 9)

             Player         Squad  Sh SoT  SoT% Sh/90 SoT/90  G/Sh G/SoT
0      Myenty Abena  Gaziantep FK   9   2  22.2  0.44   0.10  0.11  0.50
1     Tammy Abraham      Beşiktaş  32  16  50.0  2.31   1.15  0.19  0.38
2         Yaw Ackah   Kayserispor   2   1  50.0  0.98   0.49  0.00  0.00
3  Emmanuel Agbadou      Beşiktaş   9   4  44.4  0.81   0.36  0.11  0.25
4         Dan Agyei   Kocaelispor  46  17  37.0  2.02   0.75  0.11  0.29

In [24]:
print(misc_temiz.shape)
misc_temiz.head()

(608, 9)

             Player         Squad Fls Fld Off Crs Int TklW 2CrdY
0      Myenty Abena  Gaziantep FK  22  17   1   1  14   21     0
1     Tammy Abraham      Beşiktaş  25  12   9   4   6    2     0
2         Yaw Ackah   Kayserispor   2   2   0   0   1    0     0
3  Emmanuel Agbadou      Beşiktaş  16   5   1   3  13   15     0
4         Dan Agyei   Kocaelispor  27  26   7  65   4    3     0

In [25]:
print(playing_temiz.shape)
playing_temiz.head()

(739, 9)

             Player         Squad Mn/MP Mn/Start Compl Subs Mn/Sub unSub   PPM
0          Alp Abay   Antalyaspor   NaN      NaN     0    0    NaN     1   NaN
1      Myenty Abena  Gaziantep FK    80       85    17    3     44     4  1.09
2     Tammy Abraham      Beşiktaş    69       78     5    3     24     0  1.78
3         Yaw Ackah   Kayserispor    61       77     0    1     31     0  0.67
4  Emmanuel Agbadou      Beşiktaş    83       90    11    1     11     1  1.67

In [10]:
# Tüm 4 dataframe için başlık temizliği
std = std[std["Player"] != "Player"]
shooting = shooting[shooting["Player"] != "Player"]
misc = misc[misc["Player"] != "Player"]
playing = playing[playing["Player"] != "Player"]

# Şimdi sayı dönüşümünü yap
std["Min"] = std["Min"].str.replace(",", "").astype(int)

# Kontrol
print(std["Min"].dtype)
print(std.shape)

int64
(585, 25)

In [11]:
sayi_sutunlari = ["MP", "Starts", "90s", "Gls", "Ast", "PK", "PKatt", "CrdY", "CrdR"]
std[sayi_sutunlari] = std[sayi_sutunlari].apply(pd.to_numeric, errors="coerce")

print(std.dtypes)
print(std.shape)

Rk          object
Player      object
Nation      object
Pos         object
Squad       object
Age         object
Born        object
MP           int64
Starts       int64
Min          int64
90s        float64
Gls          int64
Ast          int64
G+A         object
G-PK        object
PK           int64
PKatt        int64
CrdY         int64
CrdR         int64
Gls.1       object
Ast.1       object
G+A.1       object
G-PK.1      object
G+A-PK      object
Matches     object
dtype: object
(585, 25)

In [12]:
# SHOOTING
shooting = shooting[shooting["Player"] != "Player"]
sayi_shooting = ["Sh", "SoT", "SoT%", "Sh/90", "SoT/90", "G/Sh", "G/SoT"]
shooting[sayi_shooting] = shooting[sayi_shooting].apply(pd.to_numeric, errors="coerce")

# MISC
misc = misc[misc["Player"] != "Player"]
sayi_misc = ["Fls", "Fld", "Off", "Crs", "Int", "TklW", "2CrdY"]
misc[sayi_misc] = misc[sayi_misc].apply(pd.to_numeric, errors="coerce")

# PLAYING
playing = playing[playing["Player"] != "Player"]
sayi_playing = ["Mn/MP", "Mn/Start", "Compl", "Subs", "Mn/Sub", "unSub", "PPM"]
playing[sayi_playing] = playing[sayi_playing].apply(pd.to_numeric, errors="coerce")

In [14]:
std_temiz = std[["Player", "Nation", "Pos", "Squad", "Age", "Born", "MP", "Starts", "Min", "90s", "Gls", "Ast", "PK", "PKatt", "CrdY", "CrdR"]]
shooting_temiz = shooting[["Player", "Squad", "Sh", "SoT", "SoT%", "Sh/90", "SoT/90", "G/Sh", "G/SoT"]]
misc_temiz = misc[["Player", "Squad", "Fls", "Fld", "Off", "Crs", "Int", "TklW", "2CrdY"]]
playing_temiz = playing[["Player", "Squad", "Mn/MP", "Mn/Start", "Compl", "Subs", "Mn/Sub", "unSub", "PPM"]]

In [15]:
print("std_temiz:", std_temiz.shape)
print("shooting_temiz:", shooting_temiz.shape)
print("misc_temiz:", misc_temiz.shape)
print("playing_temiz:", playing_temiz.shape)

std_temiz: (585, 16)
shooting_temiz: (585, 9)
misc_temiz: (585, 9)
playing_temiz: (711, 9)